const data = 
   ['<!----> <!----> <!----> <!----> <!----> <!----> <!----> <div><p class="system"><i class="icon level-icon" style="background-image:url(https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png)"></i><span class="nick">luizfelipe0213453757</span> gave the Streamer <span>1</span> likes!</p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->',
      '<div><p><i class="icon level-icon" style="background-image: url(&quot;https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png&quot;);"></i><!----><!----><!----><!----><span class="nick">Kenay Magalhães</span><span class="">Kssksksk</span></p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->',
      '<div><p><i class="icon level-icon" style="background-image: url(&quot;https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png&quot;);"></i><i class="icon manager-icon"></i><!----><!----><!----><span class="nick">Canal Do McVinni</span><span class="admin-im">QUAL ERA O NICK DELE ;-;</span></p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->',
      '<div><p><i class="icon level-icon" style="background-image: url(&quot;https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png&quot;);"></i><!----><!----><!----><!----><span class="nick">joaodias</span><span class="">My SUMMER CAR</span></p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->',
      '<div><p><i class="icon level-icon" style="background-image: url(&quot;https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png&quot;);"></i><!----><!----><!----><!----><span class="nick">Kenay Magalhães</span><span class="">Friday kskskssksk</span></p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->',
      '<div><p><i class="icon level-icon" style="background-image: url(&quot;https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png&quot;);"></i><!----><!----><!----><!----><span class="nick">peh1999pr99</span><span class="">KKKKKKKKKK</span></p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->',
      '<div><p><i class="icon level-icon" style="background-image: url(&quot;https://d1m6wfg60yssal.cloudfront.net/SCIMC/system_source/ic_live_anchor1.png&quot;);"></i><!----><!----><!----><!----><span class="nick">juniorsoft</span><span class="">Fala ai gera boa noite</span></p></div> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!---->']

module.exports = data;